# Generated by Django 3.2 on 2021-04-12 18:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a9d21e4f-73b2-4350-9487-912856933a9b'), primary_key=True, serialize=False)),
                ('title', models.CharField(default='Sunboard', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('x', models.SmallIntegerField()),
                ('y', models.SmallIntegerField()),
                ('z', models.SmallIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunboard.board')),
            ],
        ),
    ]
